language: python

# Run jobs on container-based infrastructure, can be overridden per job

matrix:
  include:
    # Extra includes for OSX since python language is not available by default on OSX
    - os: osx
      language: generic
      env: PYTHON_VER=3.6
    - os: osx
      language: generic
      env: PYTHON_VER=3.7


    - os: linux
      language: generic  # No need to set Python version since its conda
      env: PYTHON_VER=3.6
    - os: linux
      language: generic
      env: PYTHON_VER=3.7


before_install:
    # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

    # Install the Python environment
  - source devtools/travis-ci/before_install.sh
  - python -V

install:

    # Create test environment for package
  - python devtools/scripts/create_conda_env.py -n=test -p=$PYTHON_VER devtools/conda-envs/test_env.yaml
    # Activate the test environment
  - conda activate test
    # Build and install package
  - python setup.py develop --no-deps


script:
  - pytest -v --cov=sunback sunback/tests/

notifications:
    email: false

after_success:
  - codecov


name: sunback

addons:
  apt:
    sources:
      - sourceline: 'conda-forge'
      - sourceline: 'defaults'
      -
    packages:
      - arrow-0.15.4
      - astropy-3.2.3
      - atomicwrites-1.3.0
      - attrs-19.3.0
      - binaryornot-0.4.4
      - blas-1.0
      - ca-certificates-2019.9.11
      - certifi-2019.9.11
      - cffi-1.13.2
      - chardet-3.0.4
      - click-7.0
      - colorama-0.4.1
      - cookiecutter-1.6.0
      - cryptography-2.8
      - cycler-0.10.0
      - entrypoints-0.3
      - flake8-3.7.9
      - flake8-polyfill-1.0.2
      - flake8-quotes-2.1.1
      - freetype-2.10.0
      - future-0.18.2
      - icc_rt-2019.0.0
      - icu-64.2
      - idna-2.8
      - importlib_metadata-0.23
      - intel-openmp-2019.4
      - jinja2-2.10.3
      - jinja2-time-0.2.0
      - jpeg-9c
      - kiwisolver-1.1.0
      - libblas-3.8.0
      - libcblas-3.8.0
      - libclang-9.0.0
      - liblapack-3.8.0
      - libpng-1.6.37
      - libtiff-4.1.0
      - lz4-c-1.8.3
      - markupsafe-1.1.1
      - matplotlib-3.1.2
      - matplotlib-base-3.1.2
      - mccabe-0.6.1
      - mkl-2019.4
      - mkl-service-2.3.0
      - more-itertools-7.2.0
      - numpy-1.17.3
      - olefile-0.46
      - openssl-1.1.1d
      - packaging-19.2
      - pep8-naming-0.9.1
      - pillow-6.2.1
      - pip-19.3.1
      - pluggy-0.13.0
      - poyo-0.5.0
      - psutil-5.6.5
      - py-1.8.0
      - pycodestyle-2.5.0
      - pycparser-2.19
      - pyflakes-2.1.1
      - pyopenssl-19.0.0
      - pyparsing-2.4.5
      - pyqt-5.12.3
      - pysocks-1.7.1
      - pytesseract-0.3.0
      - pytest-5.3.0
      - pytest-arraydiff-0.3
      - pytest-astropy-0.6.0
      - pytest-astropy-header-0.1.1
      - pytest-doctestplus-0.4.0
      - pytest-openfiles-0.4.0
      - pytest-remotedata-0.3.1
      - python-3.7.3
      - python-dateutil-2.8.1
      - qt-5.12.5
      - requests-2.22.0
      - scipy-1.3.1
      - setuptools-41.6.0
      - six-1.13.0
      - sqlite-3.30.1
      - tk-8.6.9
      - tornado-6.0.3
      - urllib3-1.25.7
      - vc-14.1
      - vs2015_runtime-14.16.27012
      - wcwidth-0.1.7
      - wheel-0.33.6
      - whichcraft-0.6.1-
      - win_inet_pton-1.1.0
      - wincertstore-0.2
      - xz-5.2.4
      - zipp-0.6.0
      - zlib-1.2.11
      - zstd-1.4.4


