name: GitCloudRunHourly

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  run-task:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gillyspace27/sunback-ci:latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install sunback package from checked out code
        run: pip install .

      - name: Configure AWS credentials for OIDC
        id: aws-creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::940506845164:role/Github_Web_Identity
          aws-region: us-east-2
          audience: sts.amazonaws.com

      - name: Execute the script
        run: |
          python sunback/run/run_server_github.py